// phrases.js

// Phrases data
const phrases = {
    
    hindi: [
        "नमस्ते (Namaste) - Hello",
        "धन्यवाद (Dhanyavad) - Thank you",
        "कैसे हैं आप? (Kaise hain aap?) - How are you?",
        "मुझे मदद चाहिए (Mujhe madad chahiye) - I need help",
        "कितने का है? (Kitne ka hai?) - How much is this?",
        "अलविदा (Alvida) – Goodbye",
        "कृपया (Kripya) – Please",
        "हाँ (Haan) – Yes",
        "नहीं (Nahi) – No",
        "माफ़ कीजिए (Maaf kijiye) – Excuse me",
        "शौचालय कहाँ है? (Shauchalay kahan hai?) – Where is the restroom?",
        "यह कितना है? (Yeh kitna hai?) – How much does this cost?",
        "मुझे मदद चाहिए (Mujhe madad chahiye) – I need help",
        "आपका नाम क्या है? (Aapka naam kya hai?) – What is your name?",
        "मेरा नाम... है (Mera naam... hai) – My name is...",
        "मुझे समझ नहीं आया (Mujhe samajh nahi aaya) – I don’t understand",
        "मुझे खेद है (Mujhe khed hai) – I’m sorry",
        "क्या आप अंग्रेजी बोलते हैं? (Kya aap Angrezi bolte hain?) – Can you speak English?",
        "मैं खो गया हूँ (Main kho gaya hoon) – I’m lost",
        "मुझे भूख लगी है (Mujhe bhook lagi hai) – I’m hungry",
        "मुझे प्यास लगी है (Mujhe pyaas lagi hai) – I’m thirsty",
        "चियर्स (Cheers) – Cheers",
    ],
    tamil: [
        "வணக்கம் (Vanakkam) - Hello",
        "நன்றி (Nandri) - Thank you",
        "எப்படி இருக்கிறீர்கள்? (Eppadi irukkirirgal?) - How are you?",
        "உதவி வேண்டும் (Uthavi vendum) - I need help",
        "இது எவ்வளவு? (Idhu evvalavu?) - How much is this?",
        "விடைபெறுகிறேன் (Vidaipeṟugiṟēṉ) – Goodbye",
        "தயவுசெய்து (Thayavu seidhu) – Please",
        "ஆம் (Aam) – Yes",
        "இல்லை (Illai) – No",
        "மன்னிக்கவும் (Mannikkavum) – Excuse me",
        "கழிப்பிடம் எங்கே? (Kazhippidam engē?) – Where is the restroom?",
        "இது எவ்வளவு? (Idhu evvalavu?) – How much does this cost?",
        "எனக்கு உதவி தேவை (Enakku udhavi thevai) – I need help",
        "உங்கள் பெயர் என்ன? (Ungal peyar enna?) – What is your name?",
        "என் பெயர்... (En peyar...) – My name is...",
        "எனக்கு புரியவில்லை (Enakku puriyavillai) – I don’t understand",
        "எனக்கு மன்னிக்கவும் (Enakku mannikkavum) – I’m sorry",
        "நீங்கள் ஆங்கிலம் பேசுகிறீர்களா? (Neengal Angilam pesugirirkala?) – Can you speak English?",
        "நான் தவறாக வந்துவிட்டேன் (Naan thavaraaga vandhuvittēn) – I’m lost",
        "எனக்கு பசிக்கிறது (Enakku pasikkiradhu) – I’m hungry",
        "எனக்கு தாகம் (Enakku thagam) – I’m thirsty",
        "வாழ்த்துக்கள் (Vazhthukkal) – Cheers",
    ],
    telugu: [
        "నమస్తే (Namaste) - Hello",
        "ధన్యవాదాలు (Dhanyavadalu) - Thank you",
        "మీరు ఎలా ఉన్నారు? (Meeru ela unnaru?) - How are you?",
        "నాకు సహాయం కావాలి (Naaku sahayam kavali) - I need help",
        "ఇది ఎంత? (Idi entha?) - How much is this?",
        "వీడ్కోలు (Veedkolu) – Goodbye",
        "దయచేసి (Dayachesi) – Please",
        "అవును (Avunu) – Yes",
        "లేదు (Ledu) – No",
        "క్షమించండి (Kshaminchandi) – Excuse me",
        "టాయిలెట్ ఎక్కడ ఉంది? (Toilet ekkada undi?) – Where is the restroom?",
        "ఇది ఎంత? (Idi entha?) – How much does this cost?",
        "మీ పేరు ఏమిటి? (Mee peru emiti?) – What is your name?",
        "నా పేరు... (Naa peru...) – My name is...",
        "నాకు అర్థం కాలేదు (Naaku artham kaaledu) – I don’t understand",
        "క్షమించండి (Kshaminchandi) – I’m sorry",
        "మీరు ఇంగ్లీష్ మాట్లాడగలరా? (Meeru English maatladagalaaraa?) – Can you speak English?",
        "నేను తప్పిపోయాను (Nenu tappipoyaanu) – I’m lost",
        "నాకే ఆకలేసింది (Naake aakalesindi) – I’m hungry",
        "నాకే దాహం (Naake daaham) – I’m thirsty",
        "శుభాకాంక్షలు (Shubhaakaankshalu) – Cheers",
    ],
    marathi: [
        "नमस्कार (Namaskār) – Hello",
        "धन्यवाद (Dhanyawād) – Thank you",
        "अलविदा (Alvidā) – Goodbye",
        "कृपया (Kripaya) – Please",
        "हो (Ho) – Yes",
        "नाही (Nāhī) – No",
        "माफ करा (Māf karā) – Excuse me",
        "तुम्ही कसे आहात? (Tumhī kase āhāt?) – How are you?",
        "शौचालय कुठे आहे? (Shauchalay kuthē āhē?) – Where is the restroom?",
        "हे किती आहे? (He kiti āhe?) – How much does this cost?",
        "मला मदत हवी आहे (Malā madat havī āhe) – I need help",
        "तुझं नाव काय आहे? (Tujha nāv kāy āhē?) – What is your name?",
        "माझं नाव... (Mājha nāv...) – My name is...",
        "मला समजलं नाही (Malā samazlā nāhī) – I don’t understand",
        "मला वाईट वाटतंय (Malā wāit wātatay) – I’m sorry",
        "तुम्हाला इंग्रजी येतं का? (Tumhālā Ingrajī yēt kā?) – Can you speak English?",
        "मी हरवले आहे (Mī harawale āhē) – I’m lost",
        "मला भूक लागली आहे (Malā bhūk lāglī āhē) – I’m hungry",
        "मला तहान लागली आहे (Malā tahān lāglī āhē) – I’m thirsty",
        "चिअर्स (Cheers) – Cheers",
    ],
    bengali: [
        "নমস্কার (Nomoskar) - Hello",
        "ধন্যবাদ (Dhonnobad) - Thank you",
        "আপনি কেমন আছেন? (Apni kemon achhen?) - How are you?",
        "আমাকে সাহায্য করুন (Amake shahajyo korun) - I need help",
        "এটা কত? (Eta koto?) - How much is this?",
        "বিদায় (Bidaay) – Goodbye",
        "দয়া করে (Doya kore) – Please",
        "হ্যাঁ (Hyaa) – Yes",
        "না (Naa) – No",
        "ক্ষমা করবেন (Khoma korben) – Excuse me",
        "টয়লেট কোথায়? (Toilet kothay?) – Where is the restroom?",
        "এটি কত? (Eti koto?) – How much does this cost?",
        "আমাকে সাহায্য করুন (Amake shahajyo korun) – I need help",
        "আপনার নাম কি? (Apnar naam ki?) – What is your name?",
        "আমার নাম... (Amar naam...) – My name is...",
        "আমি বুঝতে পারছি না (Ami bujhte parchhi na) – I don’t understand",
        "দুঃখিত (Dukkhito) – I’m sorry",
        "আপনি কি ইংরেজি বলতে পারেন? (Apni ki English bolte paren?) – Can you speak English?",
        "আমি পথ হারিয়েছি (Ami poth hariyechi) – I’m lost",
        "আমি ক্ষুধার্ত (Ami khudhartho) – I’m hungry",
        "আমি তৃষ্ণার্ত (Ami trishnarto) – I’m thirsty",
        "চিয়ার্স (Cheers) – Cheers",
    ],
    kannada: [
        "ನಮಸ್ಕಾರ (Namaskara) - Hello",
        "ಧನ್ಯವಾದಗಳು (Dhanyavadagalu) - Thank you",
        "ನೀವು ಹೇಗಿದ್ದೀರಾ? (Neenu hegiddira?) - How are you?",
        "ನನಗೆ ಸಹಾಯ ಬೇಕು (Nanage sahaya beku) - I need help",
        "ಇದು ಎಷ್ಟು? (Idu eshtu?) - How much is this?",
        "ವಿದಾಯ (Vidāya) – Goodbye",
        "ದಯವಿಟ್ಟು (Dayavittu) – Please",
        "ಹೌದು (Haudu) – Yes",
        "ಇಲ್ಲ (Ill) – No",
        "ಕ್ಷಮಿಸಿ (Kshamisi) – Excuse me",
        "ನೀವು ಹೇಗಿದ್ದೀರಾ? (Nīvu hegiddīrā?) – How are you?",
        "ಶೌಚಾಲಯ ಎಲ್ಲಿದೆ? (Shauchalaya ellide?) – Where is the restroom?",
        "ಇದು ಎಷ್ಟು? (Idhu eshtu?) – How much does this cost?",
        "ನನಗೆ ಸಹಾಯ ಬೇಕು (Nanage sahāya bēku) – I need help",
        "ನಿಮ್ಮ ಹೆಸರು ಏನು? (Nimma hesaru enu?) – What is your name?",
        "ನನ್ನ ಹೆಸರು... (Nanna hesaru...) – My name is...",
        "ನನಗೆ ಅರ್ಥವಾಗುತ್ತಿಲ್ಲ (Nanage arthavagutilla) – I don’t understand",
        "ಕ್ಷಮಿಸಿ (Kshamisi) – I’m sorry",
        "ನೀವು ಇಂಗ್ಲಿಷ್ ಮಾತಾಡುತ್ತೀರಾ? (Nīvu English mātāḍuttīrā?) – Can you speak English?",
        "ನಾನು ತಪ್ಪಿಸಿಕೊಂಡಿದ್ದೇನೆ (Nānu tappisikonduiddēne) – I’m lost",
        "ನನಗೆ ಹಸಿವು (Nanage hasivu) – I’m hungry",
        "ನನಗೆ ತಿರ್ಟಿ (Nanage tirti) – I’m thirsty",
        "ಚೀರ್ಸ್(Cīrs) - Cheers",
    ],
    malayalam: [
        "നമസ്കാരം (Namaskaram) - Hello",
        "നന്ദി (Nandi) - Thank you",
        "നിങ്ങൾ എങ്ങനെയുണ്ട്? (Ningal enganeyundu?) - How are you?",
        "എനിക്ക് സഹായം വേണം (Enikku sahayam venam) - I need help",
        "ഇതിന് എത്ര വില? (Ithin ethra vila?) - How much is this?",
        "വിട (Vida) – Goodbye",
        "ദയവായി (Dayavaayi) – Please",
        "അതെ (Athe) – Yes",
        "ഇല്ല (Illa) – No",
        "ക്ഷമിക്കണം (Kshamikkanam) – Excuse me",
        "ശൗചാലയം എവിടെയാണ്? (Shouchalayam evideya?) – Where is the restroom?",
        "എന്റെ പേര്... (Ente peru...) – My name is...",
        "എനിക്ക് മനസ്സിലാകുന്നില്ല (Enikku manassilakunnilla) – I don’t understand",
        "ക്ഷമിക്കണം (Kshamikkanam) – I’m sorry",
        "നിങ്ങൾ ഇംഗ്ലീഷ് സംസാരിക്കുമോ? (Ningal English samsarikkumo?) – Can you speak English?",
        "ഞാൻ വഴിപിഴച്ചു (Njaan vazhipizhachu) – I’m lost",
        "എനിക്ക് വിശക്കും (Enikku vishakkum) – I’m hungry",
        "എനിക്ക് ദാഹം (Enikku daham) – I’m thirsty",
        "Cheers - സൽപാനം (Salpanam)",
    ],
    gujarati: [
        "નમસ્તે (Namaste) - Hello",
        "આભાર (Aabhar) - Thank you",
        "તમે કેમ છો? (Tame kem cho?) - How are you?",
        "મને મદદ જોઈશે (Mane madad joieche) - I need help",
        "આ કેટલી કિંમત છે? (Aa ketli kimat chhe?) - How much is this?",
        "આવજો (Aavjo) – Goodbye",
        "કૃપા કરીને (Krupa karine) – Please",
        "હા (Haan) – Yes",
        "ના (Na) – No",
        "માફ કરશો (Maaf karsho) – Excuse me",
        "શૌચાલય ક્યાં છે? (Shauchalay kya chhe?) – Where is the restroom?",
        "તમારું નામ શું છે? (Tamaru naam shu chhe?) – What is your name?",
        "મારું નામ... છે (Maru naam... chhe) – My name is...",
        "મને સમજી શકાતું નથી (Mane samji shakatun nathi) – I don’t understand",
        "મને ખેદ છે (Mane khed chhe) – I’m sorry",
        "તમે અંગ્રેજી બોલી શકો છો? (Tame Angreji boli shako cho?) – Can you speak English?",
        "હું ભૂલાઈ ગયો છું (Hun bhulai gayo chhun) – I’m lost",
        "મને ભૂખ લાગી છે (Mane bhukh lagi chhe) – I’m hungry",
        "મને તરસ લાગી છે (Mane taras lagi chhe) – I’m thirsty",
        "Cheers - શુભેચ્છાઓ (Shubhechchhao)",
    ],
    rajasthani: [
        "राम राम (Ram Ram) - Hello",
        "धन्यवाद (Dhanyavaad) - Thank you",
        "तुम कसा हो? (Tum kasa ho?) - How are you?",
        "मने मदद चईए (Mane madad chahiye) - I need help",
        "यो कितने को है? (Yo kitne ko hai?) - How much is this?",
        "अलविदा (Alvida) – Goodbye",
        "कृपा कर (Kripa kar) – Please",
        "हाँ (Haan) – Yes",
        "ना (Na) – No",
        "माफ करजो (Maaf karjo) – Excuse me",
        "शौचालय कहाँ है? (Shauchalay kahan hai?) – Where is the restroom?",
        "थारो नांव के है? (Tharo naav ke hai?) – What is your name?",
        "मारो नांव... है (Maro naav... hai) – My name is...",
        "मने समझ में नी आयो (Mane samajh me ni aayo) – I don’t understand",
        "मने माफ करजो (Mane maaf karjo) – I’m sorry",
        "तुम अंग्रेजी बोलो हो? (Tum Angreji bolo ho?) – Can you speak English?",
        "हूं गुम हो गयो (Hun gum ho gayo) – I’m lost",
        "मने भूख लागी है (Mane bhukh lagi hai) – I’m hungry",
        "मने प्यास लागी है (Mane pyas lagi hai) – I’m thirsty",
        "Cheers - खुश रहो (Khush raho)",
    ],
    punjabi: [
        "ਸਤ ਸ੍ਰੀ ਅਕਾਲ (Sat Sri Akaal) - Hello",
        "ਧੰਨਵਾਦ (Dhanvaad) - Thank you",
        "ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ? (Tusi kiven ho?) - How are you?",
        "ਮੈਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ (Mainu madad chahidi hai) - I need help",
        "ਇਹ ਕਿੰਨਾ ਹੈ? (Eh kina hai?) - How much is this?",
        "ਅਲਵਿਦਾ (Alvida) – Goodbye",
        "ਕਿਰਪਾ ਕਰਕੇ (Kirpa karke) – Please",
        "ਹਾਂ (Haan) – Yes",
        "ਨਹੀਂ (Nahi) – No",
        "ਮਾਫ ਕਰਨਾ (Maaf karna) – Excuse me",
        "ਸ਼ੌਚਾਲਿਆ ਕਿੱਥੇ ਹੈ? (Shauchalaya kithe hai?) – Where is the restroom?",
        "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ? (Tuhada naam ki hai?) – What is your name?",
        "ਮੇਰਾ ਨਾਮ... ਹੈ (Mera naam... hai) – My name is...",
        "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆਈ (Mainu samajh nahi aayi) – I don’t understand",
        "ਮੈਨੂੰ ਮਾਫ ਕਰਨਾ (Mainu maaf karna) – I’m sorry",
        "ਤੁਸੀਂ ਅੰਗਰੇਜ਼ੀ ਬੋਲਦੇ ਹੋ? (Tusi Angrezi bolde ho?) – Can you speak English?",
        "ਮੈਂ ਰਸਤਾ ਭੁੱਲ ਗਿਆ ਹਾਂ (Main rasta bhul gaya haan) – I’m lost",
        "ਮੈਨੂੰ ਭੁੱਖ ਲੱਗੀ ਹੈ (Mainu bhukh lagi hai) – I’m hungry",
        "ਮੈਨੂੰ ਪਿਆਸ ਲੱਗੀ ਹੈ (Mainu pyaas lagi hai) – I’m thirsty",
        "Cheers - ਖੁਸ਼ੀਆਂ (Khushiyan)",
    ],
    assamese: [
        "নমস্কাৰ (Nomoskar) - Hello",
        "ধন্যবাদ (Dhonyobad) - Thank you",
        "আপুনি কেনে আছেন? (Apuni kene aase?) - How are you?",
        "মোৰ সহায় লাগিব (Mor xohay lagibo) - I need help",
        "এইটো কিমান? (Eitu kiman?) - How much is this?",
        "বিদায় (Bidai) – Goodbye",
        "অনুগ্ৰহ কৰি (Onugroho kori) – Please",
        "হয় (Hoy) – Yes",
        "নহয় (Nohoy) – No",
        "মাফ কৰিব (Maf koribo) – Excuse me",
        "শৌচালয় ক'ত? (Shouchaloy kot?) – Where is the restroom?",
        "আপোনাৰ নাম কি? (Aaponar naam ki?) – What is your name?",
        "মোৰ নাম... (Mor naam...) – My name is...",
        "মই বুজা নাই (Moi buza nai) – I don’t understand",
        "মই দু:খিত (Moi du:kheeto) – I’m sorry",
        "আপুনি ইংৰাজী ক'ব পাৰে নেকি? (Apuni Engraji kobo pare ne?) – Can you speak English?",
        "মই পথ হেৰুৱাই পেলাইছো (Moi poth heruwaai pelaisou) – I’m lost",
        "মোৰ ভোক লাগিছে (Mor bhok lagise) – I’m hungry",
        "মোৰ তৰস লাগিছে (Mor toras lagise) – I’m thirsty",
        "Cheers - জীয়ে থকাঁ (Jiye thoka)",
    ],
    odia: [
        "ନମସ୍କାର (Namaskar) - Hello",
        "ଧନ୍ୟବାଦ (Dhanyabaad) - Thank you",
        "ତୁମେ କେମିତି ଅଛ? (Tume kemiti achha?) - How are you?",
        "ମୋତେ ସହାଯ୍ୟ ଆବଶ୍ୟକ (Mote sahajya aabasyak) - I need help",
        "ଏହା କେତେ? (Eha kete?) - How much is this?",
        "ବିଦାୟ (Bidāya) – Goodbye",
        "ଦୟାକରି (Dayākari) – Please",
        "ହଁ (Haan) – Yes",
        "ନାହିଁ (Nahīṅ) – No",
        "ମାଫ କରନ୍ତୁ (Māph karantu) – Excuse me",
        "ଶୌଚାଳୟ କେଉଁଠି ଅଛି? (Shouchālaya keunthi achhi?) – Where is the restroom?",
        "ତୁମର ନାମ କ’ଣ? (Tumara nāma kaṇa?) – What is your name?",
        "ମୋର ନାମ... (Mora nāma...) – My name is...",
        "ମୁଁ ବୁଝି ପାରୁନି (Mū̃ bujhi pārunī) – I don’t understand",
        "ମୁଁ ଦୁଃଖିତ (Mū̃ duḥkhita) – I’m sorry",
        "ତୁମେ ଇଂରାଜୀ କହିପାରିବ? (Tume inrajī kahipāriba?) – Can you speak English?",
        "ମୁଁ ହେରାଇଗଲି (Mū̃ herāi gali) – I’m lost",
        "ମୋତେ ଭୋକ ଲାଗିଛି (Mote bhok lāgi chhi) – I’m hungry",
        "ମୋତେ ତରସ ଲାଗିଛି (Mote taras lāgi chhi) – I’m thirsty",
        "Cheers - ଜୀବନ ସନ୍ତୋଷ (Jeevana santosha)",
    ],
    kashmiri: [
        "السلام علیکم (Asalam Alaikum) - Hello",
        "شکریہ (Shukriya) - Thank you",
        "خداحافظ (Khuda Hafiz) - Goodbye",
        "مہربانی کرنہ (Meharbani Karna) - Please",
        "ہاں (Haan) - Yes",
        "نہیں (Nahi) - No",
        "معاف کریں (Maaf Keren) - Excuse me",
        "تُہند چھ کیا حال؟ (Tuhund ch kya haal?) - How are you?",
        "بیتھ کز چھ؟ (Bayth kuz chhe?) - Where is the restroom?",
        "یہ کتنے کا چھ؟ (Ye kitne ka chhe?) - How much is this?",
        "میہ کھیہ مدد درکار چھ (Mye kyah madad darkar chhe) - I need help",
        "تُہند ناؤ چھ کیا؟ (Tuhund naw ch kya?) - What is your name?",
        "میہ ناؤ چھ... (Mye naw ch...) - My name is...",
        "میہ نہ سمجھ گژھان (Mye neh samaj gashaan) - I don’t understand",
        "میہ چھ افسوس (Mye chhe afsos) - I’m sorry",
        "کیا تُہند انگریزی ہند چھ؟ (Kya tuhund Angrezi hund chhe?) - Can you speak English?",
        "میہ پتہ واتھ چھ (Mye path wat chhe) - I’m lost",
        "میہ کھانی چھ بھوک (Mye khan chhe bhukh) - I’m hungry",
        "میہ چھ پیاس لگی (Mye chhe pyaas lagi) - I’m thirsty",
        "چیرز (Cheers) - Cheers",
    ],
                            
};

// DOM Elements
const tabs = document.querySelectorAll(".lang-tab");
const phrasesContainer = document.getElementById("phrases-container");

// Add event listeners to language tabs
tabs.forEach((tab) => {
    tab.addEventListener("click", () => {
        // Remove active class from all tabs
        tabs.forEach((tab) => tab.classList.remove("active"));
        // Add active class to clicked tab
        tab.classList.add("active");

        // Get language phrases
        const lang = tab.getAttribute("data-lang");
        const langPhrases = phrases[lang];

        // Update phrases container
        phrasesContainer.innerHTML = `
            <h2>Common Phrases in ${lang.charAt(0).toUpperCase() + lang.slice(1)}</h2>
            <ul>
                ${langPhrases.map((phrase) => `<li>${phrase}</li>`).join("")}
            </ul>
        `;
    });
});

// Initialize with the first tab
tabs[0].click();
